project_name: Jellycli

before:
  hooks:
    - go mod download
builds:
  - id: default
    goos:
      - linux
      - windows
    goarch:
      - amd64
      # - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - id: default
    replacements:
      linux: Linux
      windows: Windows
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: true
  prerelease: auto

